import Image from 'next/image'
// import fs from 'fs/promises'
import path from 'path'
import Head from 'next/head'

export default function Home() {
  return (
    <div className='container'>
      <Head>
        <title>Events App with Next.js</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>

      <main>
        <h1 className='large-text'>WELCOME</h1>
      </main>
    </div>
  )
}

// export async function getStaticProps() {
//   console.log('re-generating')
//   const filePath = path.join(process.cwd(), 'dummy-data.js')
//   const jsonData = await fs.readFile(filePath)
//   const data = JSON.parse(jsonData)

//   return {
//     props: {
//       events: data
//     },
//     revalidate: 10
//   }
// }
